### ISSUE TITLE
How to make it compile latest android 9

### ISSUE THREAD

**Issue by bgman111111** [TwrpBuilder/android_device_generic_twrpbuilder#1]
Put how to be made to compile. It missing vendorsetup.mk this mean when normal person run lunch dit wont show , what has to be compiled. This mean it has to be put in common on boardconfig.mk from device. This mean not only has to be put in boardconfig.mk from device but has to be put other things, like mtk.mk This bring more issues as nobody know where has to be put thIS SHITS. device_model.mk baordcondif.mk this mean peoples like you every day are more STUPID. you are indirecty insulting peoples. When you buy something a car, first you have to pass driving license, to know how drive car. What has happend if first you buy car, this is like twrpbuilder generaral has been explained. ZERO

**Comment by Surendrajat** [comment]
Mr SmartPants. You're not first **Normal Person** to use it which raises few questions about your definition of **Normal**. I suspect you meant **Normies**, not **Normal Person**.
Or, are you suggesting that people who're creating and using these free software (without giving a fuck about what you think) are **Abnormal**? 
If this is STUPID and you're not, then improve it, or you're proving yourself worse posting pointless comments.
Also, now that you've mentioned insult, I think this direct link can help you greatly, https://www.youtube.com/watch?v=MZYQ3tSuSWY
